name: Build and Deploy to CapRover

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create deployment tarball
        run: |
          tar --exclude=node_modules \
            --exclude=.git \
            --exclude=data \
            --exclude=.next \
            --exclude=.github \
            --exclude=deploy.tar \
            -cvf deploy.tar .

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Deploy to CapRover Instance
        run: |
          caprover deploy \
            --caproverUrl "${{ secrets.CAPROVER_SERVER }}" \
            --appToken "${{ secrets.CAPROVER_APP_TOKEN }}" \
            --appName "${{ secrets.CAPROVER_APP_NAME }}" \
            --tarFile ./deploy.tar
